allure.results.directory=./target/allure-results
quarkus.http.port=9090

# configure your datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=secret
quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/demo}
quarkus.hibernate-orm.schema-management.strategy=update